name: build borgbot

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/rust-build-and-test.yml
    with:
      package: borgapi
