name: build borgapi

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths:
      - borgbot/**
      - Cargo.toml
      - Cargo.lock
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/rust-build-and-test.yml
    with:
      package: borgapi
