name: deploy ui

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      FLY_API_TOKEN:
        required: true
        description: Fly API token
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy ui to fly.io
    uses: ./.github/workflows/deploy-fly-app.yaml
    with:
      dockerfile: config/borgui/Dockerfile
      config: config/borgui/fly.dev.toml
    secrets:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}