name: build and test rust

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to build'
        required: true
        type: string
  workflow_call:
    inputs:
      package:
        description: 'Package to build'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build and test {{ inputs.package }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build -p {{ inputs.package }} --verbose
      - name: Run tests
        run: cargo test -p {{ inputs.package }} --verbose
